openapi: 3.1.0
info:
  title: Kolas.Ai public API - OpenAPI 3.1
  description: |-
    This is a Kolas.Ai application's public API based on the OpenAPI 3.1 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io).

    Some useful links:
    - [The Kolas.Ai repository](https://github.com/kolasai)

  termsOfService: https://kolas.ai/terms/
  contact:
    email: info@kolas.ai
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: https://swagger.io
servers:
  - url: https://app.kolas.ai/api/v1
tags:
  - name: predictions
    description: Operations about predictions
    externalDocs:
      description: Find out more
      url: https://kolas.ai/documentation
  - name: user
    description: Operations about user
paths:
  /predict:
    post:
      tags:
        - predictions
      summary: Predict a message category
      description: Returns a predicted category of message by a configured dataset in a project
      operationId: predict
      requestBody:
        $ref: '#/components/requestBodies/PredictionRequest'
      responses:
        '200':
          $ref: '#/components/responses/PredictionResponse'
        '400':
          $ref: '#/components/responses/Error400'
        '404':
          $ref: '#/components/responses/Error404'
        '422':
          $ref: '#/components/responses/Error422'
        '5XX':
          $ref: '#/components/responses/Error5XX'
      security:
        - api_key: [ ]
components:
  schemas:
    Message:
      required:
        - message
      type: object
      properties:
        message:
          type: string
          maxLength: 5120
          examples:
            - What did you do yesterday?
    Prediction:
      type: object
      properties:
        categories:
          description:
            List of supported project's categories
          type: array
          examples:
            - [ Neutral, Insult, Spam ]
        category:
          description:
            Predicted category
          type: string
          examples:
            - Neutral
        message:
          type: string
          description:
            Sent message for prediction
          examples:
            - What did you do yesterday?
    Error:
      type: object
      properties:
        errors:
          type: array
        message:
          type: string
      required:
        - message
  responses:
    PredictionResponse:
      description: successful operation
      content:
        application/json:
          schema:
            type: object
            properties:
              predictions:
                type: array
                items:
                  $ref: '#/components/schemas/Prediction'
    Error400:
      description: Invalid ID supplied
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Error404:
      description: Project not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Error422:
      description: Validation exception
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Error5XX:
      description: Unexpected error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
  requestBodies:
    PredictionRequest:
      required: true
      description: Ask for a forecast for the message.
      content:
        application/json:
          schema:
            type: object
            properties:
              projectId:
                description: ID of project
                type: integer
                format: int64
                minimum: 1
                examples: [3457]
              messages:
                type: array
                items:
                  $ref: '#/components/schemas/Message'
  securitySchemes:
    kolasai_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://app.kolas.ai/oauth/authorize
          scopes:
            read: Grants read access
    api_key:
      type: apiKey
      name: api_key
      in: header
